/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as PublicSignupImport } from './routes/_public/signup'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as ProtectedUpcommingAppointmentsImport } from './routes/_protected/upcomming-appointments'
import { Route as ProtectedProfileImport } from './routes/_protected/profile'
import { Route as ProtectedPhysicalAppointmentsImport } from './routes/_protected/physical-appointments'
import { Route as ProtectedPatientsImport } from './routes/_protected/patients'
import { Route as ProtectedOnlineAppointmentsImport } from './routes/_protected/online-appointments'
import { Route as ProtectedAppointmentRoomIdIndexImport } from './routes/_protected/appointment-room/$id.index'
import { Route as ProtectedAppointmentPostIdImport } from './routes/_protected/appointment/post.$id'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicSignupRoute = PublicSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const ProtectedUpcommingAppointmentsRoute =
  ProtectedUpcommingAppointmentsImport.update({
    id: '/upcomming-appointments',
    path: '/upcomming-appointments',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedProfileRoute = ProtectedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedPhysicalAppointmentsRoute =
  ProtectedPhysicalAppointmentsImport.update({
    id: '/physical-appointments',
    path: '/physical-appointments',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedPatientsRoute = ProtectedPatientsImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedOnlineAppointmentsRoute =
  ProtectedOnlineAppointmentsImport.update({
    id: '/online-appointments',
    path: '/online-appointments',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedAppointmentRoomIdIndexRoute =
  ProtectedAppointmentRoomIdIndexImport.update({
    id: '/appointment-room/$id/',
    path: '/appointment-room/$id/',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedAppointmentPostIdRoute = ProtectedAppointmentPostIdImport.update(
  {
    id: '/appointment/post/$id',
    path: '/appointment/post/$id',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_protected/online-appointments': {
      id: '/_protected/online-appointments'
      path: '/online-appointments'
      fullPath: '/online-appointments'
      preLoaderRoute: typeof ProtectedOnlineAppointmentsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/patients': {
      id: '/_protected/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedPatientsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/physical-appointments': {
      id: '/_protected/physical-appointments'
      path: '/physical-appointments'
      fullPath: '/physical-appointments'
      preLoaderRoute: typeof ProtectedPhysicalAppointmentsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/upcomming-appointments': {
      id: '/_protected/upcomming-appointments'
      path: '/upcomming-appointments'
      fullPath: '/upcomming-appointments'
      preLoaderRoute: typeof ProtectedUpcommingAppointmentsImport
      parentRoute: typeof ProtectedImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupImport
      parentRoute: typeof PublicImport
    }
    '/_protected/appointment/post/$id': {
      id: '/_protected/appointment/post/$id'
      path: '/appointment/post/$id'
      fullPath: '/appointment/post/$id'
      preLoaderRoute: typeof ProtectedAppointmentPostIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/appointment-room/$id/': {
      id: '/_protected/appointment-room/$id/'
      path: '/appointment-room/$id'
      fullPath: '/appointment-room/$id'
      preLoaderRoute: typeof ProtectedAppointmentRoomIdIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedOnlineAppointmentsRoute: typeof ProtectedOnlineAppointmentsRoute
  ProtectedPatientsRoute: typeof ProtectedPatientsRoute
  ProtectedPhysicalAppointmentsRoute: typeof ProtectedPhysicalAppointmentsRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedUpcommingAppointmentsRoute: typeof ProtectedUpcommingAppointmentsRoute
  ProtectedAppointmentPostIdRoute: typeof ProtectedAppointmentPostIdRoute
  ProtectedAppointmentRoomIdIndexRoute: typeof ProtectedAppointmentRoomIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOnlineAppointmentsRoute: ProtectedOnlineAppointmentsRoute,
  ProtectedPatientsRoute: ProtectedPatientsRoute,
  ProtectedPhysicalAppointmentsRoute: ProtectedPhysicalAppointmentsRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedUpcommingAppointmentsRoute: ProtectedUpcommingAppointmentsRoute,
  ProtectedAppointmentPostIdRoute: ProtectedAppointmentPostIdRoute,
  ProtectedAppointmentRoomIdIndexRoute: ProtectedAppointmentRoomIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/online-appointments': typeof ProtectedOnlineAppointmentsRoute
  '/patients': typeof ProtectedPatientsRoute
  '/physical-appointments': typeof ProtectedPhysicalAppointmentsRoute
  '/profile': typeof ProtectedProfileRoute
  '/upcomming-appointments': typeof ProtectedUpcommingAppointmentsRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/appointment/post/$id': typeof ProtectedAppointmentPostIdRoute
  '/appointment-room/$id': typeof ProtectedAppointmentRoomIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/online-appointments': typeof ProtectedOnlineAppointmentsRoute
  '/patients': typeof ProtectedPatientsRoute
  '/physical-appointments': typeof ProtectedPhysicalAppointmentsRoute
  '/profile': typeof ProtectedProfileRoute
  '/upcomming-appointments': typeof ProtectedUpcommingAppointmentsRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/appointment/post/$id': typeof ProtectedAppointmentPostIdRoute
  '/appointment-room/$id': typeof ProtectedAppointmentRoomIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/online-appointments': typeof ProtectedOnlineAppointmentsRoute
  '/_protected/patients': typeof ProtectedPatientsRoute
  '/_protected/physical-appointments': typeof ProtectedPhysicalAppointmentsRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/upcomming-appointments': typeof ProtectedUpcommingAppointmentsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_protected/appointment/post/$id': typeof ProtectedAppointmentPostIdRoute
  '/_protected/appointment-room/$id/': typeof ProtectedAppointmentRoomIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/online-appointments'
    | '/patients'
    | '/physical-appointments'
    | '/profile'
    | '/upcomming-appointments'
    | '/login'
    | '/signup'
    | '/appointment/post/$id'
    | '/appointment-room/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/online-appointments'
    | '/patients'
    | '/physical-appointments'
    | '/profile'
    | '/upcomming-appointments'
    | '/login'
    | '/signup'
    | '/appointment/post/$id'
    | '/appointment-room/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/online-appointments'
    | '/_protected/patients'
    | '/_protected/physical-appointments'
    | '/_protected/profile'
    | '/_protected/upcomming-appointments'
    | '/_public/login'
    | '/_public/signup'
    | '/_protected/appointment/post/$id'
    | '/_protected/appointment-room/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/_public"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/online-appointments",
        "/_protected/patients",
        "/_protected/physical-appointments",
        "/_protected/profile",
        "/_protected/upcomming-appointments",
        "/_protected/appointment/post/$id",
        "/_protected/appointment-room/$id/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/login",
        "/_public/signup"
      ]
    },
    "/_protected/online-appointments": {
      "filePath": "_protected/online-appointments.tsx",
      "parent": "/_protected"
    },
    "/_protected/patients": {
      "filePath": "_protected/patients.tsx",
      "parent": "/_protected"
    },
    "/_protected/physical-appointments": {
      "filePath": "_protected/physical-appointments.tsx",
      "parent": "/_protected"
    },
    "/_protected/profile": {
      "filePath": "_protected/profile.tsx",
      "parent": "/_protected"
    },
    "/_protected/upcomming-appointments": {
      "filePath": "_protected/upcomming-appointments.tsx",
      "parent": "/_protected"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_public/signup": {
      "filePath": "_public/signup.tsx",
      "parent": "/_public"
    },
    "/_protected/appointment/post/$id": {
      "filePath": "_protected/appointment/post.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/appointment-room/$id/": {
      "filePath": "_protected/appointment-room/$id.index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
